### ISSUE TITLE
BUG -  var mailchimp_database

### ISSUE THREAD

**Issue by dfagnan** [fivetran/dbt_mailchimp_source#7] opened 2021-12-05 02:36 UTC
The readme references the ability to control the source database with `mailchimp_database` however `models/src_mailchimp.yml` references `database` instead leading to an inability to control the database as expected. 

Line here: https://github.com/fivetran/dbt_mailchimp_source/blob/main/models/src_mailchimp.yml#L6

Happy to create a PR but don't have permissions :)

**Comment by JoeMark17** [comment] 2021-12-05 16:30
Hey @dfagnan thanks for raising this issue and finding the exact spot where the issue is occurring!

The spot in the source yml is exactly where the change needs to happen. You can indeed still use the variable 'database' to control the database used by the package, but I feel it would be best to be in line with our readme and change this to 'mailchimp_database'.

If you are willing to open a PR to update the naming in the source yml then that would be great and we can integrate this into the next path release early next week!

Thanks again so much for bringing this to our attention and helping make this package better. Let me know if you have any questions about opening the PR.

**Comment by fivetran-sheringuyen** [comment] 2021-12-09 22:59
Hi @dfagnan, thank you so much for opening this issue. This really helped make the package better for us and everyone else in the community! We definitely appreciate the contribution and hope that you continue collaborating with us in the future. I've just cut the releases for both `dbt_mailchimp` and `dbt_mailchimp_source` so keep a lookout for the new releases coming shortly. I'm going to close this issue now but if you have anything else to add, please don't hesitate to let us know!

**Closed by fivetran-sheringuyen** 2021-12-09 22:59 UTC
Labels: bug
